### ISSUE TITLE
Error Main Thread

### ISSUE THREAD

**Issue by rikesh3** [gdfonda/Terminator-Vision#2]
In AnalyzeScene(), when PhotoCapture.CreateAsync(false, OnPhotoCaptureCreated) gets called, we get a "INTERNAL_CALL_Instantiate_Internal can only be called from the main thread" error message. Any ideas what we are doing wrong?

**Comment by jaseva** [comment]
I'm receiving the similar error messages:

INTERNAL_CALL_Instantiate_Internal can only be called from the main thread.
Constructors and field initializers will be executed from the loading thread when loading a scene.
Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
UnityEngine.VR.WSA.WebCam.PhotoCapture:CreateAsync(Boolean, OnCaptureResourceCreatedCallback)
Hud:AnalyzeScene() (at Assets/Scripts/Hud.cs:122)
Hud:Tick(Object) (at Assets/Scripts/Hud.cs:48)

Transform has SetIsDispatchInterested present when destroying the hierarchy. Systems must deregister themselves in Deactivate.
UnityEngine.Canvas:SendWillRenderCanvases()

Transform has SetIsHierarchyDispatchInterested present when destroying the hierarchy. Systems must deregister themselves in Deactivate.
UnityEngine.Canvas:SendWillRenderCanvases()

System is not interested in this transform, SetSystemInterested may only be called on transforms that are set interested.

These might be Unity errors?  I believe this project was created with Unity 5.5.0f3 and I'm running Unity 5.6.0b10.  I also tested with previous Unity versions 5.5.x ad 5.6.x as I could not find the version that this project was initially created in.

**Comment by neon-ninja** [comment]
Similar:

System.ArgumentException was unhandled
Message: An unhandled exception of type 'System.ArgumentException' occurred in mscorlib.ni.dll
Additional information: get_isActiveAndEnabled can only be called from the main thread.
Constructors and field initializers will be executed from the loading thread when loading a scene.
Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.

**Comment by neon-ninja** [comment]
I don't think Unity supports modifying objects outside the main thread as it isn't thread safe. I think you'd have to use coroutines https://docs.unity3d.com/400/Documentation/ScriptReference/index.Coroutines_26_Yield.html

**Comment by jaseva** [comment]
Thanks for the link neon-ninja, I suspect it may have something to do with the object hierarchy (parent/ child) for the canvas within Unity being buggy for the new Unity versions based on similar error messages reported by other users that I read within other discussion forums.  Will continue investigating.   I'm looking forward to being able to successfully deploy this app with the cognitive services running.

**Comment by neon-ninja** [comment]
Give https://github.com/neon-ninja/Terminator-Vision/commit/b007c19c65938c5f5ee6956b1d46e5672ec3af7a a try, see if that works

**Comment by jaseva** [comment]
Many thanks, I'll test it out this evening!  Cheers for the link.

**Comment by jaseva** [comment]
Hi @neon-ninja I'm not receiving the previous Unity console error messages as before so thanks for sharing your code for the Hud.cs script.  I also tested with the same version of Unity that you had used (Unity 5.6.0b7).  

This is probably a separate thread issue however I noticed that the Thermal GameObject does not maintain head tracking with the main camera while testing the device.  Is that the intentional design of the app?  I assumed that the Thermal GameObject should also track with head movement?

![image](https://cloud.githubusercontent.com/assets/5480431/23783317/ba6fda6c-0528-11e7-9013-73d6759a3f98.png)

Also I see 11 warning messages in the console concerning some of the scripts.  I'm assuming as the original master repository was published with an earlier version of Unity?

**Comment by neon-ninja** [comment]
Actually, I used Unity 5.5.2f1

**Comment by jaseva** [comment]
Hmm, I'll have to play around with it a bit more today.  Did you successfully deploy and the app tests fine on your device?

**Comment by sniejadlik** [comment]
I have finally gotten this to successfully deploy on 5.6beta. The main thread error was all from the Timer thread being the main driver for calling all the functions.  I do not know enough about thread locking or proper protocol with it but by just shifting the action to the update frame and setting it to a simple check against Time.deltaTime its essentially doing the same thing but without being run on an unsafe thread. Everything I have looked at points to referencing stage properties and assets while outside of the main thread as the problem.  Could anyone with knowledge of proper threading or coroutine usage and locking practices fill in as to why this is?

Again the simple fix for me was to just remove AnalyzeScene() from Tick, cancel the Tick thread all together since it serves no purpose other than frame free timing.  and then change Update to this.

void Update()
    {
        timeCounter += Time.deltaTime;
        if (timeCounter >= 20)
        {
            timeCounter = 0;
            AnalyzeScene();
        }
    }

**Comment by neon-ninja** [comment]
@branchbark yes. it's safe to ignore warnings

**Comment by neon-ninja** [comment]
@sniejadlik Unity is not thread safe. One can't modify objects that are bound to the main thread outside the main thread. Your method works, so does https://github.com/neon-ninja/Terminator-Vision/commit/b007c19c65938c5f5ee6956b1d46e5672ec3af7a

**Comment by gdfonda** [comment]
@neon-ninja's changes have been merged into the master branch to fix this problem. many thanks to him. It appears that this threading bug affected running in the Unity IDE (and consequently for remoting and debugging) but not on the HoloLens device itself (but that may simply be true in my local environment). Closing this issue for now, but feel free to re-open the subject if you feel like it. Threading in Unity is a fascinating topic.
